Repository eclipse-edc/Technology-Azure, pull requests merged in 2023-07, with the labels that each got.

#19 fix: compile errors in event publisher
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventGridPublisher.java
Labels: bug

#21 chore: add DEPENDENCIES file and NOTICE file
  .github/workflows/dependency-review.yml
  DEPENDENCIES
  NOTICE.md
Labels: documentation

#26 docs: add decision record about using PostgreSQL API
  docs/developer/decision-records/2023-07-12_use_cosmos_postgres_api/README.md
Labels: documentation

#30 feat(ci): moved Cosmos tests to scheduled workflow
  .github/workflows/run-cosmos-tests.yaml
  .github/workflows/verify.yaml
Labels: enhancement, github_actions

#31 build: use .github dependency chech
  .github/workflows/dependency-check.yml
Labels: enhancement
