Repository eclipse-edc/Technology-Azure, pull requests merged in 2024-03, with the labels that each got.

#157 fix: compilation
  DEPENDENCIES
  build.gradle.kts
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-blob/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
  gradle.properties
Labels: bug

#163 fix: settings fields in extensions
  DEPENDENCIES
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventExtension.java
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventGridConfig.java
  system-tests/azure-blob-transfer-tests/src/test/java/org/eclipse/edc/test/system/blob/BlobTransferIntegrationTest.java
Labels: bug

#164 fix: compilation
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventGridPublisher.java
  extensions/control-plane/provision/provision-blob/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/store/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreTest.java
Labels: bug

#167 feat: adapt upstream package changes (Keys)
  DEPENDENCIES
  extensions/common/azure/azure-test/build.gradle.kts
  extensions/common/azure/azure-test/src/testFixtures/java/org/eclipse/edc/azure/testfixtures/AbstractAzureBlobTest.java
  extensions/control-plane/store/transfer-process-store-cosmos/src/test/resources/schema.sql
  gradle/libs.versions.toml
  system-tests/azure-blob-transfer-fixtures/build.gradle.kts
  system-tests/azure-blob-transfer-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/blob/ConsumerConstants.java
  system-tests/azure-blob-transfer-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/blob/ProviderConstants.java
Labels: bug, breaking-change

#170 build: fix compilation
  DEPENDENCIES
  build.gradle.kts
  gradle/libs.versions.toml
  system-tests/runtimes/azure-data-factory-transfer-consumer/build.gradle.kts
  system-tests/runtimes/azure-data-factory-transfer-provider/build.gradle.kts
  system-tests/runtimes/azure-storage-transfer-consumer/build.gradle.kts
  system-tests/runtimes/azure-storage-transfer-provider/build.gradle.kts
Labels: build

#172 chore(compile): fix compile errors after EDC refactor
  DEPENDENCIES
  build.gradle.kts
  extensions/common/azure/azure-blob-core/src/main/java/org/eclipse/edc/azure/blob/AzureSasToken.java
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventExtension.java
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/AzureEventGridPublisher.java
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/edc/azure/event/TransferProcessDto.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/AzureProvisionExtension.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectContainerProvisionedResource.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisioner.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageResourceDefinition.java
  extensions/control-plane/provision/provision-blob/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-blob/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisionerTest.java
  extensions/control-plane/store/asset-index-cosmos/build.gradle.kts
  extensions/control-plane/store/asset-index-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndexTest.java
  extensions/control-plane/store/contract-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractdefinition/CosmosContractDefinitionStoreTest.java
  extensions/control-plane/store/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreTest.java
  extensions/control-plane/store/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreTest.java
  gradle/libs.versions.toml
  system-tests/azure-blob-transfer-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/blob/BlobTransferParticipant.java
  system-tests/azure-blob-transfer-tests/src/test/java/org/eclipse/edc/test/system/blob/BlobTransferIntegrationTest.java
  system-tests/azure-data-factory-tests/src/test/java/org/eclipse/edc/test/system/blob/AzureDataFactoryTransferIntegrationTest.java
Labels: enhancement
